### ISSUE TITLE
implement the hierarchical config

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/botrex#4]
This issue should be addressed after #3 

- [x] import the package of the hierarchical function
- [x] document the command flexibility we should provide to the `telegram-updater` script
- [x] implement  `telegram-updater` and simulate the behavior in two different telegram channels

**Comment by berli0z** [comment]
-imported hierarchical config and implemented in tester.py and
- implemented as bin/channel_update.py
- documented as argument when running the python script (-h) and in the configuration files
