### ISSUE TITLE
configure the bot on a server

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/botrex#5]
- provide access to @berli0z 
- configure the crontab in the way we want
- spread the channel: https://t.me/fbTREXupdates

**Comment by vecna** [comment]
please test it!

**Comment by vecna** [comment]
```
you@computer:~/botrex$ python3 bin/channel_update.py 
Traceback (most recent call last):
  File "bin/channel_update.py", line 16, in <module>
    timeframe = int(args.timeframe)
ValueError: invalid literal for int() with base 10: 'hours_as_number'
```
the requirements are installed! we can proceed to configure the crontab and/or the service

**Comment by vecna** [comment]
What do you think about this logo for the telegram channel?
![Uploading fbtrex_updates.png…]()

**Comment by vecna** [comment]
what do you think of this picture for the update channel? It is a temporary thing, but I was looking for some kind of _arrow_ and I end up to use a bow and arrow :P it is temporarly anyway (and I don't know if I can change on my own)
![fbtrex_updates](https://user-images.githubusercontent.com/89555/50044355-83e3be80-0082-11e9-95dc-6e065700f067.png)

**Comment by berli0z** [comment]
The logo is great! I just added it!
Also installed venv on the server and now the bot is running with the updates too! We have a daily update on the channel and the inline bot is active on a detached screen and runs on reboot!
CLOSING ;)
